### ISSUE TITLE
Run samples

### ISSUE THREAD

**Issue by nucliweb** [LadyScream/Love2D-Creative-Coding#1] opened 2018-10-04 14:03 UTC
Hi!

I tried to run the samples in Mac OS X, I've dragged and drop the folder or main.lua to the window App and run from terminal `/Applications/love.app/Contents/MacOS/love 000-Triangle`, but I can't see anything.

Can you add the instructions on README file, please?

Thanks

**Comment by LadyScream** [comment] 2018-10-05 19:57
Hey!

The problem is that when I was working with this code, Löve was in the 0.10.2 version, but now it's on 11.0 and they changed the color notation in this version, instead of the colors ranging from 0 to 255, they range from 0 to 1.

I'm going to update them now!

**Comment by LadyScream** [comment] 2018-10-05 20:08
Fixed on: 9a1832aea954a1fe110903cf3252dce247b721ef

**Closed as completed** 2018-10-05 20:08 UTC
Labels: bug
